# Họ tên: Nguyễn Vũ Hải
# Lớp: CNTT K18 CLC
# Mã SV: DTC195480201CLC0006

In [2]:
import numpy as np
import pandas as pd
import random

# Câu 1:

Ý a:

In [4]:
arrFinal = np.arange(100).reshape(20,5)
print(arrFinal)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


Ý B:

In [5]:
print(f"Tổng hàng 15 của mảng: {sum(arrFinal[14])}")

Tổng hàng 15 của mảng: 360


Ý c:

In [7]:
ArrDf = pd.DataFrame(arrFinal)
display(ArrDf)
print(ArrDf.info())

0   1   2   3   4
0    0   1   2   3   4
1    5   6   7   8   9
2   10  11  12  13  14
3   15  16  17  18  19
4   20  21  22  23  24
5   25  26  27  28  29
6   30  31  32  33  34
7   35  36  37  38  39
8   40  41  42  43  44
9   45  46  47  48  49
10  50  51  52  53  54
11  55  56  57  58  59
12  60  61  62  63  64
13  65  66  67  68  69
14  70  71  72  73  74
15  75  76  77  78  79
16  80  81  82  83  84
17  85  86  87  88  89
18  90  91  92  93  94
19  95  96  97  98  99

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     int32
 1   1       20 non-null     int32
 2   2       20 non-null     int32
 3   3       20 non-null     int32
 4   4       20 non-null     int32
dtypes: int32(5)
memory usage: 528.0 bytes
None


# Câu 2

In [8]:
df_salary = pd.read_csv("Salaries.csv")
df_salary.head()

C:\Users\mamto\AppData\Local\Temp\ipykernel_204\15317537.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_salary = pd.read_csv("Salaries.csv")


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [13]:
print(f"Các loại nghề nghiệp hiện có : {df_salary.JobTitle.unique()}")
print(f"Tổng số các nghề là: {len(df_salary.JobTitle.unique())}")

Các loại nghề nghiệp hiện có : ['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY'
 'CAPTAIN III (POLICE DEPARTMENT)' 'WIRE ROPE CABLE MAINTENANCE MECHANIC'
 ... 'Conversion' 'Cashier 3' 'Not provided']
Tổng số các nghề là: 2159


In [17]:
df_salary.BasePay = pd.to_numeric(df_salary.BasePay, errors='coerce')
arrYearGroupBy = df_salary[["Year","BasePay"]].groupby("Year",as_index = False).mean()
print(f"Lương trung bình theo năm là")
display(arrYearGroupBy)

Lương trung bình theo năm là


Year       BasePay
0  2011  63595.956517
1  2012  65436.406857
2  2013  69630.030216
3  2014  66564.421924

In [35]:
print(f"Shape 0 của df: {len(df_salary)}")
print(f"{df_salary.columns}")
Condition1 = df_salary[(df_salary.EmployeeName == "Not provided") | (df_salary.EmployeeName == "Not Provided")]
arrDropName = df_salary.drop(Condition1.index)
display(arrDropName)

Shape 0 của df: 148654
Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148645  148646   Carolyn A Wilson   
148647  148648     Joann Anderson   
148648  148649        Leon Walker   
148649  148650      Roy I Tillery   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay OvertimePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.0   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   245131.88   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   106088.18   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00    56120.71   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.0   
...                                                ...        ...         ...   
148645                       Human Services Technician       0.00        0.00   
148647                     Communications Dispatcher 2       0.00        0.00   
148648                                       Custodian       0.00        0.00   
148649                                       Custodian       0.00        0.00   
148653                      Counselor, Log Cabin Ranch       0.00        0.00   

         OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0       400184.25      NaN  567595.43         567595.43  2011    NaN   
1       137811.38      NaN  538909.28         538909.28  2011    NaN   
2         16452.6      NaN  335279.91         335279.91  2011    NaN   
3        198306.9      NaN  332343.61         332343.61  2011    NaN   
4       182234.59      NaN  326373.19         326373.19  2011    NaN   
...           ...      ...        ...               ...   ...    ...   
148645       0.00     0.00       0.00              0.00  2014    NaN   
148647       0.00     0.00       0.00              0.00  2014    NaN   
148648       0.00     0.00       0.00              0.00  2014    NaN   
148649       0.00     0.00       0.00              0.00  2014    NaN   
148653    -618.13     0.00    -618.13           -618.13  2014    NaN   

               Agency Status  
0       San Francisco    NaN  
1       San Francisco    NaN  
2       San Francisco    NaN  
3       San Francisco    NaN  
4       San Francisco    NaN  
...               ...    ...  
148645  San Francisco     PT  
148647  San Francisco     PT  
148648  San Francisco     PT  
148649  San Francisco     PT  
148653  San Francisco     PT  

[148648 rows x 13 columns]

# Câu 3:

In [36]:
#importing libraries
import pandas as pd
import sqlite3
 

In [37]:
conn = sqlite3.connect("testdb.db")

In [49]:
df_salary.to_sql("sal_table", conn, index=False, if_exists="replace")

148654

# Cách 1

In [50]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


In [51]:
%sql sqlite:///testdb.db

In [ ]:
SELECT SUM(salary) AS "Total Salary"
FROM employees
WHERE salary > 25000;

In [112]:
%sql SELECT SUM(TotalPay) FROM sal_table WHERE Year=2012 and JobTitle LIKE '%firefighter%'

 * sqlite:///testdb.db
Done.


[(151861396.66999996,)]

In [52]:
%sql SELECT * FROM sal_table LIMIT 20;

 * sqlite:///testdb.db
Done.


[(1, 'NATHANIEL FORD', 'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY', 167411.18, '0.0', '400184.25', None, 567595.43, 567595.43, 2011, None, 'San Francisco', None),
 (2, 'GARY JIMENEZ', 'CAPTAIN III (POLICE DEPARTMENT)', 155966.02, '245131.88', '137811.38', None, 538909.28, 538909.28, 2011, None, 'San Francisco', None),
 (3, 'ALBERT PARDINI', 'CAPTAIN III (POLICE DEPARTMENT)', 212739.13, '106088.18', '16452.6', None, 335279.91, 335279.91, 2011, None, 'San Francisco', None),
 (4, 'CHRISTOPHER CHONG', 'WIRE ROPE CABLE MAINTENANCE MECHANIC', 77916.0, '56120.71', '198306.9', None, 332343.61, 332343.61, 2011, None, 'San Francisco', None),
 (5, 'PATRICK GARDNER', 'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)', 134401.6, '9737.0', '182234.59', None, 326373.19, 326373.19, 2011, None, 'San Francisco', None),
 (6, 'DAVID SULLIVAN', 'ASSISTANT DEPUTY CHIEF II', 118602.0, '8601.0', '189082.74', None, 316285.74, 316285.74, 2011, None, 'San Francisco', None),
 (7, 'ALSON LEE', 'BATTALION CHIEF, (FIRE DEPARTMENT)', 92492.01, '89062.9', '134426.14', None, 315981.05, 315981.05, 2011, None, 'San Francisco', None),
 (8, 'DAVID KUSHNER', 'DEPUTY DIRECTOR OF INVESTMENTS', 256576.96, '0.0', '51322.5', None, 307899.46, 307899.46, 2011, None, 'San Francisco', None),
 (9, 'MICHAEL MORRIS', 'BATTALION CHIEF, (FIRE DEPARTMENT)', 176932.64, '86362.68', '40132.23', None, 303427.55, 303427.55, 2011, None, 'San Francisco', None),
 (10, 'JOANNE HAYES-WHITE', 'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)', 285262.0, '0.0', '17115.73', None, 302377.73, 302377.73, 2011, None, 'San Francisco', None),
 (11, 'ARTHUR KENNEY', 'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)', 194999.39, '71344.88', '33149.9', None, 299494.17, 299494.17, 2011, None, 'San Francisco', None),
 (12, 'PATRICIA JACKSON', 'CAPTAIN III (POLICE DEPARTMENT)', 99722.0, '87082.62', '110804.3', None, 297608.92, 297608.92, 2011, None, 'San Francisco', None),
 (13, 'EDWARD HARRINGTON', 'EXECUTIVE CONTRACT EMPLOYEE', 294580.02, '0.0', '0.0', None, 294580.02, 294580.02, 2011, None, 'San Francisco', None),
 (14, 'JOHN MARTIN', 'DEPARTMENT HEAD V', 271329.03, '0.0', '21342.59', None, 292671.62, 292671.62, 2011, None, 'San Francisco', None),
 (15, 'DAVID FRANKLIN', 'BATTALION CHIEF, (FIRE DEPARTMENT)', 174872.64, '74050.3', '37424.11', None, 286347.05, 286347.05, 2011, None, 'San Francisco', None),
 (16, 'RICHARD CORRIEA', 'COMMANDER III, (POLICE DEPARTMENT)', 198778.01, '73478.2', '13957.65', None, 286213.86, 286213.86, 2011, None, 'San Francisco', None),
 (17, 'AMY HART', 'DEPARTMENT HEAD V', 268604.57, '0.0', '16115.86', None, 284720.43, 284720.43, 2011, None, 'San Francisco', None),
 (18, 'SEBASTIAN WONG', 'CAPTAIN, EMERGENCYCY MEDICAL SERVICES', 140546.87, '119397.26', '18625.08', None, 278569.21, 278569.21, 2011, None, 'San Francisco', None),
 (19, 'MARTY ROSS', 'BATTALION CHIEF, (FIRE DEPARTMENT)', 168692.63, '69626.12', '38115.47', None, 276434.22, 276434.22, 2011, None, 'San Francisco', None),
 (20, 'ELLEN MOFFATT', 'ASSISTANT MEDICAL EXAMINER', 257510.59, '880.16', '16159.5', None, 274550.25, 274550.25, 2011, None, 'San Francisco', None)]

# Cách 2:

In [53]:
%sql result << SELECT * FROM sal_table;

 * sqlite:///testdb.db
Done.
Returning data to local variable result


In [55]:
result = pd.DataFrame(result)

In [56]:
display(result)

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25          None  567595.43         567595.43   
1          245131.88     137811.38          None  538909.28         538909.28   
2          106088.18       16452.6          None  335279.91         335279.91   
3           56120.71      198306.9          None  332343.61         332343.61   
4             9737.0     182234.59          None  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year Notes         Agency Status  
0       2011  None  San Francisco   None  
1       2011  None  San Francisco   None  
2       2011  None  San Francisco   None  
3       2011  None  San Francisco   None  
4       2011  None  San Francisco   None  
...      ...   ...            ...    ...  
148649  2014  None  San Francisco     PT  
148650  2014  None  San Francisco   None  
148651  2014  None  San Francisco   None  
148652  2014  None  San Francisco   None  
148653  2014  None  San Francisco     PT  

[148654 rows x 13 columns]

In [114]:
Condition2 = df_salary[(df_salary.JobTitle.str.contains("Firefighter")) & (df_salary.Year == 2012)]
print(f"Số fire fighter của năm 2012:{len(Condition2)}")
print(f"Tổng lương của nghề firefighter là : {sum(Condition2.TotalPay)}")

Số fire fighter của năm 2012:1069
Tổng lương của nghề firefighter là : 151861396.66999996
